### ISSUE TITLE
Support pure text and json format, via json in comment and md5 check.

### ISSUE THREAD

**Issue by doug** [gammons/todolist#11]
Feature Request / Proposal / Pony. 

First cool project, this is clearly a feature pony but thought I would share.
Would be nice if I was still allowed to edit the file like a todo.md in text editor of choice.

Proposal to maintain the speed and ease of the json data structure would be to put the json datastructure in a comment at the bottom of the markdown file as well as an md5 hash of the text above the comment. On read it checks the md5 and updates the json if necessary, on write it updates the text and md5. In the majority of cases the md5 is the same so no reparsing necessary and it maintains its speediness. And it gains the added benefit of being renderable with markdown.

``` markdown
# Todo
- [ ] My todo @work +project due tomorrow
- [ ] My other todo @home

# Archive
- [x] Already done @home

<!-- md5:0b34db8fb67cff70c882618d405f0b3f -->
<!-- [{"id":1,"subject":"My todo @work +project","projects":["project"],"contexts":["work"],"due":"2016-09-22","completed":false,"archived":false},{"id":2,"subject":"My other todo @home","projects":[],"contexts":["home"],"due":"","completed":false,"archived":false}] -->
```

**Comment by gammons** [comment]
@doug interesting ideas!  I see 2 of them here:

1.  Human-readable todos file format,
2.  Speed optimization based upon calculated MD5 hash.

For 1), I have definitely considered this, mainly in the context of allowing `todolist` to read + write [Todo.txt](http://todotxt.com/) files, and therefore this project would be sucked into that ecosystem.  I don't necessarily think there is a downside to doing that.  It's not like my todos.json file format is super-proprietary.  It's just a means to store the data.  What are your thoughts about that?  Or would it be nicer/better to have a markdown file instead?  Have you evaluated Todo.txt?

For 2), I definitely see the need to eventually have speed optimizations to avoid parsing the entire list.   Out of curiosity, how many todos do you have total?  For my main list that I use daily, I am up to id# 500, and running `todolist` still feels instantaneous.   So from my personal perspective, the optimization is not needed yet, but I am definitely curious to hear about your experience.

**Comment by doug** [comment]
For 1) Something very nice about human readable format. I do like the todo.txt format and that is what my todos are currently in. Often put a todo list on github so having it in markdown is just nice that github preview picks it up and renders it.
For 2) I would say I have about 300 todos, so not really hitting any speed issues yet, but was looking at adding due dates to my todo lists and saw your project. And I had been thinking about this idea previously to have my todos keep a more structured data representation in their comment so thought I would suggest it. Just seems nice to maintain a structured view of the data on disk but maintain a human text interface to it.

I see the todo.txt or todo.md file with the md5+json in a comment format as a way to have a standardized todo.txt interface with a cached machine model representation that could be a compatible superset of standard todo.txt.

I would also be happy with just todo.txt standard format. :) The ecosystem is quite large and that has a lot of benefits.
